allow-lan: true
bind-address: 127.0.0.1
dns:
  enable: false
  listen: 0.0.0.0:53
  nameserver:
    - 8.8.8.8
    - 4.4.4.4
log-level: info
mode: rule
port: 1087
proxies:
  - alterId: 2
    cipher: auto
    name: 台湾01|原生|C组中继×1.0
    network: ws
    port: 31107
    server: qzyd.qovoq.cf
    skip-cert-verify: false
    tls: true
    type: vmess
    udp: false
    uuid: 38368a52-8d1b-4e0a-bcbe-9d184c0ce79e
    ws-headers:
      Host: hinet.ddns.ddnszd.xyz
    ws-path: /
proxy-groups:
  - interval: 300
    name: PROXY
    proxies:
      - 台湾01|原生|C组中继×1.0
    type: load-balance
    url: http://www.gstatic.com/generate_204
rules:
  - IP-CIDR, 127.0.0.0/8, DIRECT
  - IP-CIDR, 10.0.0.0/8, DIRECT
  - IP-CIDR, 172.16.0.0/12, DIRECT
  - IP-CIDR, 192.168.0.0/16, DIRECT
  - GEOIP, CN, DIRECT
  - MATCH, PROXY
socks-port: 1080